on: push
jobs:
  build:
    strategy:
      matrix:
        platform: [x86, x64]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          $Env:PATH+=";C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
          msbuild /t:Restore
          msbuild /p:Platform=${{ matrix.platform }},Configuration=Release
          if ($LASTEXITCODE -ne 0) { exit 1 }
          $dir = '.\BarcodeReader\bin\${{ matrix.platform }}\Release'
          if ('${{ matrix.platform }}' -eq 'x86') {
              $sys = "$Env:WINDIR\SysWOW64"
          } else {
              $sys = "$Env:WINDIR\System32"
          }
          7z a release.zip "$dir\*.exe" "$dir\*.exe.config" "$dir\*.dll" "$sys\vcruntime140.dll" 'LICENSE'
      - if: github.ref == 'refs/heads/master'
        run: |
          cmd /c "git fetch --tags --unshallow 2>&1"
          mkdir -Force ~\.ssh
          [IO.File]::WriteAllBytes( `
              "$Env:USERPROFILE\.ssh\id_ed25519", `
              [Convert]::FromBase64String("${{ secrets.DEPLOYKEY }}"))
          cmd /c 'ssh-keyscan web.sourceforge.net > "%USERPROFILE%\.ssh\known_hosts" 2>nul'
          cmd /c "scp release.zip ddosolitary@web.sourceforge.net:/home/project-web/ddosolitary-builds/htdocs/BarcodeReader/BarcodeReader-r$(git rev-list --count HEAD)-${{ matrix.platform }}.zip 2>&1"
          if ($LASTEXITCODE -ne 0) { exit 1 }
