on: push
jobs:
  build:
    strategy:
      matrix:
        platform: [x86, x64]
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@master
      - shell: pwsh
        run: |
          $Env:PATH+=";C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
          msbuild /t:Restore
          msbuild /p:Platform=${{ matrix.platform }},Configuration=Release
          $dir = '.\BarcodeReader\bin\${{ matrix.platform }}\Release'
          if ('${{ matrix.platform }}' -eq 'x86') {
              $sys = "$Env:WINDIR\SysWOW64"
          } else {
              $sys = "$Env:WINDIR\System32"
          }
          7z a release.zip "$dir\*.exe" "$dir\*.exe.config" "$dir\*.dll" "$sys\vcruntime140.dll" 'LICENSE'
          curl.exe -fsS -T release.zip -u ddosolitary:${{ secrets.BINTRAY_KEY }} https://api.bintray.com/content/ddosolitary/dev-releases/default/default/BarcodeReader/BarcodeReader-${{ matrix.platform }}-r$(git rev-list --count HEAD).zip
          curl.exe -fsS -X POST -u ddosolitary:${{ secrets.BINTRAY_KEY }} https://api.bintray.com/content/ddosolitary/dev-releases/default/default/publish
